<?php

namespace Blogpot\ArticleBundle\Repository;

/**
 * HOMERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HOMERepository extends \Doctrine\ORM\EntityRepository
{
}
