<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.cssrewrite' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/BaseCssFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/CssRewriteFilter.php';

return $this->services['assetic.filter.cssrewrite'] = new \Assetic\Filter\CssRewriteFilter();
